services:
  - type: web
    name: socialmedia-rag
    env: python
    rootDir: .
    buildCommand: |
      set -e
      cd frontend
      npm ci
      npm run build
      cd ..
      rm -rf backend/app/static
      mkdir -p backend/app/static
      # copy built frontend into FastAPI's static dir (keeps dotfiles)
      cp -r frontend/dist/. backend/app/static/
      cd backend
      poetry install --no-root
    startCommand: cd backend && poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 20.19.4

